### PR TITLE
fix issues 13 and 14; changes to PVAlarm, PVTimeStamp.etc

### PR DESCRIPTION
**Pull request by mrkraimer**
PVAlarm, PVTimeStamp,PVControl, and PVDisplay:
The set methods now only do a put to fields that have actually changed.
In addition to fixing issues 13 and 14 a few changes were made to get rid of some compiler warnings.

I want to do some more testing before merging but I also would like Kunal and Kay to review changes.

ALSO
Kunal:

Look at README.md You decide it You want the version You created or the one I created.
Just let me know and if You want your version I will make change before any merge.

### CODE REVIEW

**Comment by kasemir** [comment]
The "README" seems to include git conflict markers like " <<<<<<< HEAD "

**Comment by kasemir** [comment]
The updates of alarm and time stamp seem to use the correct `==` vs. `equals()` operations.

For what it's worth, the tests are mostly just checking that there _is_ some result, `assertTrue(result != null)`, with a printout of the result. They don't check if the result contains any of the expected information.

Beyond that, I really don't know much about the code to make useful comments.

**Comment by mrkraimer** [comment]
I am ready for this to be merged except for README.md
Kunal:

Which version do you want?
Note that I did push a version that has conflicts but it should show what is intended.
So let me know and I will fix it.
Any other comments before a merge?

**Comment by shroffk** [comment]
> For what it's worth, the tests are mostly just checking that there is some result, assertTrue(result != null), with a printout of the result. They don't check if the result contains any of the expected information.

This can be made into another issue ticket.

The Jenkins build is still failing
https://openepics.ci.cloudbees.com/job/pvData%20(Java)%20-%20PullRequests/19/

Once the jenkins failure is resolved I will merge this and resolve the readme

**Comment by mrkraimer** [comment]
I suspect that the jenkins failure is a problem with pom.xml or with Jenkins itself.
I am not sure what should be done.
I suspect the pom.xml files in the other Java modules may have the same problem.

What to do?

**Comment by kasemir** [comment]
The error looks like an internal jenkins/maven problem related to using the wrong version of Java:
```
hudson/remoting/Launcher : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
..	at org.jvnet.hudson.maven3.agent.Maven3Main.main(Maven3Main.java:70)
ERROR: Failed to parse POMs
```

Java class version 52 is Java 8. Maybe it's executed with Java 7?

Meanwhile, one of our CS-Studio Travis setup has trouble getting Java 9.
Maybe today is a bad day for build servers that try to fetch Java?

**Comment by shroffk** [comment]
> Travis setup has trouble getting Java 9.

I have had this problem with travis on phoebus which was resolved in 2 days. There was an incorrect link in the travis part which created the container

**Comment by shroffk** [comment]
I don't see anything in the pom that states the wrong java version (which would result in a failure on travis too). I could not find where the jenkins config lives... @mrkraimer could you point me in the right direction here?

> other Java modules may have the same problem.

This could explain the failing pvAccessJava builds too...

> What to do?

not sure...I feel uncomfortable merging thing with broken CI

**Comment by ralphlange** [comment]
From the top of the Jenkins Job page:

> 
> Maven project pvData (Java) - PullRequests
> 
> Build pvData (Java/Maven) Pull Requests from GitHub.
> 
> Automatically generated job. Do not edit using the web interface.
> See [job generator repository](https://github.com/epics-base/jenkins-jobs) for details.
> Use the [issue tracker](https://github.com/epics-base/jenkins-jobs/issues) to report problems.
> 
> 

What other information do you need?

**Comment by ralphlange** [comment]
Does your local build work?

**Comment by ralphlange** [comment]
Hm.
Might be something pulled in from the epics parent pom.
Version of the sonar stuff too old?

**Pull request merged**
